import type { Recipe } from "@backbar/core";

// Layer-1 canon (spec §6.1) — classic specs as **facts**. Proportions are
// facts, not protected expression; no book prose is bundled.
//
// Ingredient references use:
//   - `category` for fully substitutable spirit families ("any gin")
//   - `tag` for sub-style substitutables ("any white rum", "sweet vermouth")
//   - `product` for ingredients where specificity matters (Campari, orgeat)
//   - `freeform` for pantry/garnish that doesn't draw from a bottle (mint,
//     egg white, citrus peels — these are in `FREEFORM_OK` in core).
//
// Citrus juices use `tag` (e.g. tag:"lime") so a "lime" product tagged
// "lime" satisfies it; this keeps canon recipes makeable without locking
// to specific SKUs.

export const CANON_RECIPES: readonly Recipe[] = [
  {
    id: "old-fashioned",
    name: "Old Fashioned",
    family: "old-fashioned",
    method: "build",
    glass: "rocks",
    ice: "large-format",
    garnish: "orange peel",
    instructions:
      "Stir bourbon, syrup, and bitters over ice until well chilled; strain over fresh large ice. Express orange peel and drop in.",
    source: "book",
    provenance: "canon",
    abv_estimate: 0.32,
    balance: { sweet: 0.2, sour: 0, bitter: 0.3, strong: 0.85, aromatic: 0.7, dilution: 0.35 },
    is_published: true,
    tags: ["classic", "spirit-forward"],
    ingredients: [
      { ref_type: "category", ref_id: "bourbon", label: "bourbon (or rye)", amount: 60, unit: "ml", optional: false, garnish: false, sort: 0 },
      { ref_type: "product", ref_id: "simple-syrup", label: "simple syrup", amount: 1, unit: "barspoon", optional: false, garnish: false, sort: 1 },
      { ref_type: "product", ref_id: "angostura-bitters", label: "Angostura bitters", amount: 2, unit: "dash", optional: false, garnish: false, sort: 2 },
      { ref_type: "freeform", ref_id: "orange-peel", label: "orange peel", amount: 1, unit: "each", optional: false, garnish: true, sort: 3 },
    ],
  },
  {
    id: "negroni",
    name: "Negroni",
    family: "spirit-forward",
    method: "stir",
    glass: "rocks",
    ice: "large-format",
    garnish: "orange peel",
    instructions: "Stir all ingredients with ice until well chilled; strain over large ice. Express orange peel.",
    source: "book",
    provenance: "canon",
    abv_estimate: 0.24,
    balance: { sweet: 0.3, sour: 0, bitter: 0.8, strong: 0.7, aromatic: 0.6, dilution: 0.4 },
    is_published: true,
    tags: ["classic", "equal-parts", "aperitivo"],
    ingredients: [
      { ref_type: "category", ref_id: "gin", label: "gin", amount: 30, unit: "ml", optional: false, garnish: false, sort: 0 },
      { ref_type: "product", ref_id: "campari", label: "Campari", amount: 30, unit: "ml", optional: false, garnish: false, sort: 1 },
      { ref_type: "tag", ref_id: "sweet-vermouth", label: "sweet vermouth", amount: 30, unit: "ml", optional: false, garnish: false, sort: 2 },
      { ref_type: "freeform", ref_id: "orange-peel", label: "orange peel", amount: 1, unit: "each", optional: false, garnish: true, sort: 3 },
    ],
  },
  {
    id: "daiquiri",
    name: "Daiquiri",
    family: "sour",
    method: "shake",
    glass: "coupe",
    ice: "none",
    garnish: "lime wheel",
    instructions: "Shake hard with ice; double-strain into chilled coupe.",
    source: "book",
    provenance: "canon",
    abv_estimate: 0.21,
    balance: { sweet: 0.35, sour: 0.7, bitter: 0.05, strong: 0.55, aromatic: 0.3, dilution: 0.5 },
    is_published: true,
    tags: ["classic", "sour", "tiki"],
    ingredients: [
      { ref_type: "tag", ref_id: "white-rum", label: "white rum", amount: 60, unit: "ml", optional: false, garnish: false, sort: 0 },
      { ref_type: "tag", ref_id: "lime", label: "fresh lime juice", amount: 22, unit: "ml", optional: false, garnish: false, sort: 1 },
      { ref_type: "product", ref_id: "simple-syrup", label: "simple syrup", amount: 15, unit: "ml", optional: false, garnish: false, sort: 2 },
      { ref_type: "freeform", ref_id: "lime-wheel", label: "lime wheel", amount: 1, unit: "each", optional: true, garnish: true, sort: 3 },
    ],
  },
  {
    id: "manhattan",
    name: "Manhattan",
    family: "spirit-forward",
    method: "stir",
    glass: "coupe",
    ice: "none",
    garnish: "brandied cherry",
    instructions: "Stir with ice until well chilled; strain into chilled coupe.",
    source: "book",
    provenance: "canon",
    abv_estimate: 0.3,
    balance: { sweet: 0.3, sour: 0, bitter: 0.25, strong: 0.75, aromatic: 0.6, dilution: 0.4 },
    is_published: true,
    tags: ["classic", "spirit-forward"],
    ingredients: [
      { ref_type: "category", ref_id: "rye", label: "rye (or bourbon)", amount: 60, unit: "ml", optional: false, garnish: false, sort: 0 },
      { ref_type: "tag", ref_id: "sweet-vermouth", label: "sweet vermouth", amount: 30, unit: "ml", optional: false, garnish: false, sort: 1 },
      { ref_type: "product", ref_id: "angostura-bitters", label: "Angostura bitters", amount: 2, unit: "dash", optional: false, garnish: false, sort: 2 },
      { ref_type: "freeform", ref_id: "brandied-cherry", label: "brandied cherry", amount: 1, unit: "each", optional: true, garnish: true, sort: 3 },
    ],
  },
  {
    id: "martini",
    name: "Martini",
    family: "spirit-forward",
    method: "stir",
    glass: "coupe",
    ice: "none",
    garnish: "lemon peel",
    instructions: "Stir with ice until very cold and well diluted; strain into chilled coupe. Express lemon peel.",
    source: "book",
    provenance: "canon",
    abv_estimate: 0.34,
    balance: { sweet: 0.1, sour: 0, bitter: 0.1, strong: 0.9, aromatic: 0.5, dilution: 0.45 },
    is_published: true,
    tags: ["classic", "spirit-forward"],
    ingredients: [
      { ref_type: "category", ref_id: "gin", label: "gin", amount: 60, unit: "ml", optional: false, garnish: false, sort: 0 },
      { ref_type: "tag", ref_id: "dry-vermouth", label: "dry vermouth", amount: 15, unit: "ml", optional: false, garnish: false, sort: 1 },
      { ref_type: "freeform", ref_id: "lemon-peel", label: "lemon peel", amount: 1, unit: "each", optional: false, garnish: true, sort: 2 },
    ],
  },
  {
    id: "margarita",
    name: "Margarita",
    family: "sour",
    method: "shake",
    glass: "rocks",
    ice: "cubed",
    garnish: "salt rim",
    instructions: "Shake all ingredients with ice; strain over fresh ice in a salt-rimmed rocks glass.",
    source: "book",
    provenance: "canon",
    abv_estimate: 0.22,
    balance: { sweet: 0.4, sour: 0.7, bitter: 0.05, strong: 0.55, aromatic: 0.4, dilution: 0.5 },
    is_published: true,
    tags: ["classic", "sour"],
    ingredients: [
      { ref_type: "tag", ref_id: "blanco-tequila", label: "blanco tequila", amount: 60, unit: "ml", optional: false, garnish: false, sort: 0 },
      { ref_type: "tag", ref_id: "orange-liqueur", label: "orange liqueur (Cointreau / triple sec)", amount: 22, unit: "ml", optional: false, garnish: false, sort: 1 },
      { ref_type: "tag", ref_id: "lime", label: "fresh lime juice", amount: 22, unit: "ml", optional: false, garnish: false, sort: 2 },
      { ref_type: "freeform", ref_id: "salt", label: "salt rim", amount: 1, unit: "each", optional: false, garnish: true, sort: 3 },
    ],
  },
  {
    id: "whiskey-sour",
    name: "Whiskey Sour",
    family: "sour",
    method: "shake",
    glass: "coupe",
    ice: "none",
    garnish: "lemon peel",
    instructions: "Dry-shake with egg white (if using), then shake again with ice; double-strain into chilled coupe.",
    source: "book",
    provenance: "canon",
    abv_estimate: 0.2,
    balance: { sweet: 0.4, sour: 0.7, bitter: 0.05, strong: 0.55, aromatic: 0.3, dilution: 0.5 },
    is_published: true,
    tags: ["classic", "sour"],
    ingredients: [
      { ref_type: "category", ref_id: "bourbon", label: "bourbon", amount: 60, unit: "ml", optional: false, garnish: false, sort: 0 },
      { ref_type: "tag", ref_id: "lemon", label: "fresh lemon juice", amount: 22, unit: "ml", optional: false, garnish: false, sort: 1 },
      { ref_type: "product", ref_id: "simple-syrup", label: "simple syrup", amount: 22, unit: "ml", optional: false, garnish: false, sort: 2 },
      { ref_type: "freeform", ref_id: "egg-white", label: "egg white", amount: 1, unit: "each", optional: true, garnish: false, sort: 3 },
      { ref_type: "freeform", ref_id: "lemon-peel", label: "lemon peel", amount: 1, unit: "each", optional: false, garnish: true, sort: 4 },
    ],
  },
  {
    id: "jungle-bird",
    name: "Jungle Bird",
    family: "tiki",
    method: "shake",
    glass: "rocks",
    ice: "cubed",
    garnish: "pineapple wedge",
    instructions: "Shake with ice; strain into rocks glass over fresh ice.",
    source: "book",
    provenance: "canon",
    abv_estimate: 0.16,
    balance: { sweet: 0.55, sour: 0.55, bitter: 0.5, strong: 0.45, aromatic: 0.4, dilution: 0.5 },
    is_published: true,
    tags: ["tiki", "tropical", "bitter"],
    ingredients: [
      { ref_type: "tag", ref_id: "blackstrap-rum", label: "blackstrap (or dark) rum", amount: 45, unit: "ml", optional: false, garnish: false, sort: 0 },
      { ref_type: "product", ref_id: "campari", label: "Campari", amount: 22, unit: "ml", optional: false, garnish: false, sort: 1 },
      { ref_type: "tag", ref_id: "pineapple", label: "pineapple juice", amount: 45, unit: "ml", optional: false, garnish: false, sort: 2 },
      { ref_type: "tag", ref_id: "lime", label: "fresh lime juice", amount: 15, unit: "ml", optional: false, garnish: false, sort: 3 },
      { ref_type: "product", ref_id: "simple-syrup", label: "simple syrup", amount: 15, unit: "ml", optional: false, garnish: false, sort: 4 },
    ],
  },
  {
    id: "mai-tai",
    name: "Mai Tai",
    family: "tiki",
    method: "shake",
    glass: "double-rocks",
    ice: "crushed",
    garnish: "mint sprig + spent lime shell",
    instructions: "Shake with cracked ice; pour unstrained into glass and top with crushed ice. Garnish with mint and spent lime shell.",
    source: "book",
    provenance: "canon",
    abv_estimate: 0.22,
    balance: { sweet: 0.45, sour: 0.6, bitter: 0.05, strong: 0.6, aromatic: 0.5, dilution: 0.5 },
    is_published: true,
    tags: ["tiki", "tropical"],
    ingredients: [
      { ref_type: "tag", ref_id: "aged-rum", label: "aged rum", amount: 30, unit: "ml", optional: false, garnish: false, sort: 0 },
      { ref_type: "tag", ref_id: "jamaican-rum", label: "Jamaican rum", amount: 30, unit: "ml", optional: false, garnish: false, sort: 1 },
      { ref_type: "product", ref_id: "orange-curacao", label: "orange curaçao", amount: 15, unit: "ml", optional: false, garnish: false, sort: 2 },
      { ref_type: "product", ref_id: "orgeat", label: "orgeat", amount: 15, unit: "ml", optional: false, garnish: false, sort: 3 },
      { ref_type: "tag", ref_id: "lime", label: "fresh lime juice", amount: 22, unit: "ml", optional: false, garnish: false, sort: 4 },
      { ref_type: "freeform", ref_id: "mint", label: "mint sprig", amount: 1, unit: "leaf", optional: false, garnish: true, sort: 5 },
    ],
  },
  {
    id: "gimlet",
    name: "Gimlet",
    family: "sour",
    method: "shake",
    glass: "coupe",
    ice: "none",
    garnish: "lime wheel",
    instructions: "Shake with ice; double-strain into chilled coupe.",
    source: "book",
    provenance: "canon",
    abv_estimate: 0.27,
    balance: { sweet: 0.4, sour: 0.7, bitter: 0.05, strong: 0.6, aromatic: 0.4, dilution: 0.5 },
    is_published: true,
    tags: ["classic", "sour"],
    ingredients: [
      { ref_type: "category", ref_id: "gin", label: "gin", amount: 60, unit: "ml", optional: false, garnish: false, sort: 0 },
      { ref_type: "tag", ref_id: "lime", label: "fresh lime juice", amount: 22, unit: "ml", optional: false, garnish: false, sort: 1 },
      { ref_type: "product", ref_id: "simple-syrup", label: "simple syrup", amount: 15, unit: "ml", optional: false, garnish: false, sort: 2 },
    ],
  },
  {
    id: "sazerac",
    name: "Sazerac",
    family: "old-fashioned",
    method: "stir",
    glass: "rocks",
    ice: "none",
    garnish: "lemon peel",
    instructions: "Rinse chilled rocks glass with absinthe and discard excess. Stir rye, syrup, and Peychaud's with ice; strain into prepared glass. Express lemon peel over the top.",
    source: "book",
    provenance: "canon",
    abv_estimate: 0.4,
    balance: { sweet: 0.2, sour: 0, bitter: 0.25, strong: 0.9, aromatic: 0.75, dilution: 0.35 },
    is_published: true,
    tags: ["classic", "spirit-forward"],
    ingredients: [
      { ref_type: "category", ref_id: "rye", label: "rye", amount: 60, unit: "ml", optional: false, garnish: false, sort: 0 },
      { ref_type: "product", ref_id: "simple-syrup", label: "simple syrup", amount: 1, unit: "barspoon", optional: false, garnish: false, sort: 1 },
      { ref_type: "product", ref_id: "peychauds-bitters", label: "Peychaud's bitters", amount: 3, unit: "dash", optional: false, garnish: false, sort: 2 },
      { ref_type: "product", ref_id: "absinthe", label: "absinthe (rinse)", amount: 1, unit: "barspoon", optional: false, garnish: false, sort: 3 },
      { ref_type: "freeform", ref_id: "lemon-peel", label: "lemon peel", amount: 1, unit: "each", optional: false, garnish: true, sort: 4 },
    ],
  },
];
