import type { FlavorProfile } from "@backbar/core";

/**
 * Corpus A — ingredient flavor profiles (authored facts; our own wording).
 *
 * The keystone of AI grounding (specs/ai-grounding-corpus.md §A): per-ingredient
 * axis contributions + descriptors + typical ABV + structural role. These make
 * balance *computable* (vs the model's self-reported guess) and are the "strong
 * descriptors" surfaced to the agent.
 *
 * Keyed by `ref` (a product slug, category id, or tag value). The tool layer
 * resolves a spec ingredient product → tag → category, so we cover all three
 * levels; the most specific match wins. Axes are 0..1 *contributions* (volume-
 * weighted on aggregate); `dilution` is method-driven and not an axis here.
 *
 * Descriptor wording is ours; accuracy was checked against public references
 * (FlavorDB2 / GoodScents / WCR lexicon) but no third-party rows are copied —
 * those sources are NonCommercial and reference-only.
 */
export const FLAVOR_PROFILES: readonly FlavorProfile[] = [
  // ── base spirits (categories) ───────────────────────────────────────────
  { ref: "gin", ref_type: "category", role: "base-spirit", typical_abv: 0.44, intensity: 0.8,
    descriptors: ["juniper", "citrus-peel", "pine", "coriander", "floral"],
    axes: { sweet: 0.05, sour: 0, bitter: 0.1, strong: 0.9, aromatic: 0.75 },
    notes: "London-dry backbone: piney juniper over citrus and spice botanicals." },
  { ref: "bourbon", ref_type: "category", role: "base-spirit", typical_abv: 0.45, intensity: 0.85,
    descriptors: ["caramel", "vanilla", "oak", "corn-sweet", "baking-spice"],
    axes: { sweet: 0.2, sour: 0, bitter: 0.1, strong: 0.9, aromatic: 0.6 } },
  { ref: "rye", ref_type: "category", role: "base-spirit", typical_abv: 0.46, intensity: 0.85,
    descriptors: ["rye-spice", "pepper", "oak", "dry", "mint"],
    axes: { sweet: 0.1, sour: 0, bitter: 0.15, strong: 0.92, aromatic: 0.65 } },
  { ref: "scotch", ref_type: "category", role: "base-spirit", typical_abv: 0.43, intensity: 0.85,
    descriptors: ["malt", "smoke", "peat", "honey", "oak"],
    axes: { sweet: 0.15, sour: 0, bitter: 0.15, strong: 0.9, aromatic: 0.7 } },
  { ref: "rum", ref_type: "category", role: "base-spirit", typical_abv: 0.43, intensity: 0.8,
    descriptors: ["molasses", "cane", "tropical", "vanilla"],
    axes: { sweet: 0.25, sour: 0, bitter: 0.05, strong: 0.88, aromatic: 0.55 } },
  { ref: "tequila", ref_type: "category", role: "base-spirit", typical_abv: 0.4, intensity: 0.8,
    descriptors: ["agave", "vegetal", "citrus", "pepper", "mineral"],
    axes: { sweet: 0.1, sour: 0.05, bitter: 0.1, strong: 0.85, aromatic: 0.6 } },
  { ref: "mezcal", ref_type: "category", role: "base-spirit", typical_abv: 0.45, intensity: 0.9,
    descriptors: ["smoke", "roasted-agave", "earth", "citrus", "mineral"],
    axes: { sweet: 0.1, sour: 0.05, bitter: 0.1, strong: 0.9, aromatic: 0.85 } },
  { ref: "brandy", ref_type: "category", role: "base-spirit", typical_abv: 0.4, intensity: 0.8,
    descriptors: ["grape", "dried-fruit", "oak", "floral", "honey"],
    axes: { sweet: 0.25, sour: 0.05, bitter: 0.05, strong: 0.85, aromatic: 0.6 } },
  { ref: "vodka", ref_type: "category", role: "base-spirit", typical_abv: 0.4, intensity: 0.4,
    descriptors: ["neutral", "clean", "faint-grain"],
    axes: { sweet: 0.02, sour: 0, bitter: 0.02, strong: 0.9, aromatic: 0.05 } },
  { ref: "spirit", ref_type: "category", role: "base-spirit", typical_abv: 0.42, intensity: 0.7,
    descriptors: ["spirituous", "warming"],
    axes: { sweet: 0.1, sour: 0, bitter: 0.1, strong: 0.9, aromatic: 0.4 },
    notes: "Generic spirit fallback when a more specific category isn't resolved." },
  { ref: "absinthe", ref_type: "category", role: "aromatic", typical_abv: 0.68, intensity: 0.95,
    descriptors: ["anise", "wormwood", "fennel", "herbal", "menthol"],
    axes: { sweet: 0.05, sour: 0, bitter: 0.2, strong: 0.95, aromatic: 0.95 },
    notes: "Used as a rinse/accent — tiny volume, huge aromatic punch." },

  // ── amari & bittering modifiers ─────────────────────────────────────────
  { ref: "amaro", ref_type: "category", role: "amaro-bitter", typical_abv: 0.28, intensity: 0.8,
    descriptors: ["bitter-herb", "root", "orange-peel", "caramel", "gentian"],
    axes: { sweet: 0.4, sour: 0, bitter: 0.75, strong: 0.4, aromatic: 0.7 } },
  { ref: "campari", ref_type: "product", role: "amaro-bitter", typical_abv: 0.24, intensity: 0.85,
    descriptors: ["bitter-orange", "rhubarb", "gentian", "clove", "red-fruit"],
    axes: { sweet: 0.35, sour: 0, bitter: 0.8, strong: 0.4, aromatic: 0.6 },
    notes: "Backbone bitter of the Negroni family." },

  // ── aromatized wines ────────────────────────────────────────────────────
  { ref: "vermouth", ref_type: "category", role: "aromatized-wine", typical_abv: 0.17, intensity: 0.55,
    descriptors: ["wine", "herbal", "wormwood", "citrus"],
    axes: { sweet: 0.3, sour: 0.1, bitter: 0.2, strong: 0.25, aromatic: 0.55 } },
  { ref: "sweet-vermouth", ref_type: "tag", role: "aromatized-wine", typical_abv: 0.16, intensity: 0.6,
    descriptors: ["red-fruit", "vanilla", "clove", "bitter-herb", "caramel"],
    axes: { sweet: 0.45, sour: 0.05, bitter: 0.2, strong: 0.22, aromatic: 0.6 } },
  { ref: "dry-vermouth", ref_type: "tag", role: "aromatized-wine", typical_abv: 0.18, intensity: 0.45,
    descriptors: ["white-wine", "grassy", "herbal", "saline", "citrus"],
    axes: { sweet: 0.12, sour: 0.15, bitter: 0.12, strong: 0.25, aromatic: 0.5 } },
  { ref: "carpano-antica", ref_type: "product", role: "aromatized-wine", typical_abv: 0.165, intensity: 0.65,
    descriptors: ["vanilla", "cocoa", "dried-cherry", "bitter-orange", "spice"],
    axes: { sweet: 0.5, sour: 0.05, bitter: 0.22, strong: 0.22, aromatic: 0.65 } },
  { ref: "dolin-dry", ref_type: "product", role: "aromatized-wine", typical_abv: 0.175, intensity: 0.45,
    descriptors: ["alpine-herb", "white-flower", "grassy", "citrus"],
    axes: { sweet: 0.12, sour: 0.15, bitter: 0.12, strong: 0.25, aromatic: 0.52 } },
  { ref: "wine", ref_type: "category", role: "aromatized-wine", typical_abv: 0.13, intensity: 0.4,
    descriptors: ["grape", "fruit", "tannin"],
    axes: { sweet: 0.2, sour: 0.2, bitter: 0.1, strong: 0.18, aromatic: 0.4 } },

  // ── liqueurs (sweeteners with flavor) ───────────────────────────────────
  { ref: "liqueur", ref_type: "category", role: "liqueur-sweet", typical_abv: 0.25, intensity: 0.65,
    descriptors: ["sweet", "flavored", "syrupy"],
    axes: { sweet: 0.7, sour: 0, bitter: 0.1, strong: 0.3, aromatic: 0.5 } },
  { ref: "orange-liqueur", ref_type: "tag", role: "liqueur-sweet", typical_abv: 0.3, intensity: 0.7,
    descriptors: ["orange-peel", "candied-citrus", "sweet", "warm-spice"],
    axes: { sweet: 0.7, sour: 0.05, bitter: 0.1, strong: 0.35, aromatic: 0.55 } },
  { ref: "cointreau", ref_type: "product", role: "liqueur-sweet", typical_abv: 0.4, intensity: 0.75,
    descriptors: ["bitter-sweet-orange", "candied-peel", "clean", "floral"],
    axes: { sweet: 0.65, sour: 0.05, bitter: 0.12, strong: 0.45, aromatic: 0.6 } },
  { ref: "orange-curacao", ref_type: "product", role: "liqueur-sweet", typical_abv: 0.3, intensity: 0.7,
    descriptors: ["orange-peel", "caramel", "brandy-warmth", "candied"],
    axes: { sweet: 0.72, sour: 0.05, bitter: 0.1, strong: 0.35, aromatic: 0.55 } },

  // ── syrups / sweeteners ─────────────────────────────────────────────────
  { ref: "syrup-simple", ref_type: "category", role: "syrup-sweet", typical_abv: 0, intensity: 0.5,
    descriptors: ["sugar", "neutral-sweet"],
    axes: { sweet: 1, sour: 0, bitter: 0, strong: 0, aromatic: 0 } },
  { ref: "syrup-rich", ref_type: "category", role: "syrup-sweet", typical_abv: 0, intensity: 0.6,
    descriptors: ["rich-sugar", "viscous", "caramel-edge"],
    axes: { sweet: 1, sour: 0, bitter: 0, strong: 0, aromatic: 0.1 },
    notes: "2:1 sugar:water — ~1.5–2× the sweetness of simple per volume." },
  { ref: "syrup", ref_type: "category", role: "syrup-sweet", typical_abv: 0, intensity: 0.55,
    descriptors: ["sweet", "flavored-sugar"],
    axes: { sweet: 0.95, sour: 0, bitter: 0, strong: 0, aromatic: 0.2 } },
  { ref: "simple-syrup", ref_type: "product", role: "syrup-sweet", typical_abv: 0, intensity: 0.5,
    descriptors: ["sugar", "neutral-sweet"],
    axes: { sweet: 1, sour: 0, bitter: 0, strong: 0, aromatic: 0 } },
  { ref: "orgeat", ref_type: "product", role: "syrup-sweet", typical_abv: 0, intensity: 0.7,
    descriptors: ["almond", "orange-flower", "nutty", "marzipan"],
    axes: { sweet: 0.9, sour: 0, bitter: 0.05, strong: 0, aromatic: 0.5 } },
  { ref: "honey", ref_type: "tag", role: "syrup-sweet", typical_abv: 0, intensity: 0.65,
    descriptors: ["honey", "floral", "rich-sweet"],
    axes: { sweet: 0.95, sour: 0, bitter: 0, strong: 0, aromatic: 0.35 } },

  // ── bitters (dash-volume aromatics) ─────────────────────────────────────
  { ref: "bitters", ref_type: "category", role: "bitters", typical_abv: 0.4, intensity: 0.95,
    descriptors: ["bitter-spice", "root", "aromatic"],
    axes: { sweet: 0, sour: 0, bitter: 0.6, strong: 0.4, aromatic: 0.9 } },
  { ref: "angostura-bitters", ref_type: "product", role: "bitters", typical_abv: 0.447, intensity: 0.95,
    descriptors: ["clove", "cinnamon", "gentian", "baking-spice", "bitter"],
    axes: { sweet: 0, sour: 0, bitter: 0.6, strong: 0.45, aromatic: 0.95 } },
  { ref: "peychauds-bitters", ref_type: "product", role: "bitters", typical_abv: 0.35, intensity: 0.9,
    descriptors: ["anise", "cherry", "floral", "light-bitter"],
    axes: { sweet: 0.05, sour: 0, bitter: 0.5, strong: 0.35, aromatic: 0.9 } },

  // ── citrus ──────────────────────────────────────────────────────────────
  { ref: "citrus", ref_type: "category", role: "citrus", typical_abv: 0, intensity: 0.75,
    descriptors: ["citrus", "tart", "bright"],
    axes: { sweet: 0.05, sour: 0.9, bitter: 0.05, strong: 0, aromatic: 0.25 } },
  { ref: "lime", ref_type: "tag", role: "citrus", typical_abv: 0, intensity: 0.78,
    descriptors: ["lime", "tart", "green", "zesty"],
    axes: { sweet: 0.05, sour: 0.95, bitter: 0.05, strong: 0, aromatic: 0.25 } },
  { ref: "lemon", ref_type: "tag", role: "citrus", typical_abv: 0, intensity: 0.75,
    descriptors: ["lemon", "tart", "bright", "floral"],
    axes: { sweet: 0.05, sour: 0.92, bitter: 0.03, strong: 0, aromatic: 0.25 } },
  { ref: "lime-juice", ref_type: "product", role: "citrus", typical_abv: 0, intensity: 0.78,
    descriptors: ["lime", "tart", "green", "zesty"],
    axes: { sweet: 0.05, sour: 0.95, bitter: 0.05, strong: 0, aromatic: 0.25 } },
  { ref: "lemon-juice", ref_type: "product", role: "citrus", typical_abv: 0, intensity: 0.75,
    descriptors: ["lemon", "tart", "bright"],
    axes: { sweet: 0.05, sour: 0.92, bitter: 0.03, strong: 0, aromatic: 0.25 } },
  { ref: "grapefruit", ref_type: "tag", role: "citrus", typical_abv: 0, intensity: 0.7,
    descriptors: ["grapefruit", "tart", "pith-bitter", "fragrant"],
    axes: { sweet: 0.15, sour: 0.7, bitter: 0.3, strong: 0, aromatic: 0.35 } },

  // ── non-citrus juices ───────────────────────────────────────────────────
  { ref: "juice", ref_type: "category", role: "juice", typical_abv: 0, intensity: 0.55,
    descriptors: ["fruit", "sweet-tart"],
    axes: { sweet: 0.45, sour: 0.3, bitter: 0, strong: 0, aromatic: 0.4 } },
  { ref: "pineapple", ref_type: "tag", role: "juice", typical_abv: 0, intensity: 0.7,
    descriptors: ["pineapple", "tropical", "sweet-tart", "foamy"],
    axes: { sweet: 0.5, sour: 0.35, bitter: 0, strong: 0, aromatic: 0.5 } },
  { ref: "pineapple-juice", ref_type: "product", role: "juice", typical_abv: 0, intensity: 0.7,
    descriptors: ["pineapple", "tropical", "sweet-tart", "foamy"],
    axes: { sweet: 0.5, sour: 0.35, bitter: 0, strong: 0, aromatic: 0.5 } },

  // ── rum sub-styles (tags) ───────────────────────────────────────────────
  { ref: "white-rum", ref_type: "tag", role: "base-spirit", typical_abv: 0.4, intensity: 0.65,
    descriptors: ["light-cane", "clean", "faint-vanilla", "grassy"],
    axes: { sweet: 0.18, sour: 0, bitter: 0.03, strong: 0.85, aromatic: 0.4 } },
  { ref: "aged-rum", ref_type: "tag", role: "base-spirit", typical_abv: 0.43, intensity: 0.8,
    descriptors: ["oak", "caramel", "dried-fruit", "molasses", "spice"],
    axes: { sweet: 0.28, sour: 0, bitter: 0.06, strong: 0.88, aromatic: 0.6 } },
  { ref: "jamaican-rum", ref_type: "tag", role: "base-spirit", typical_abv: 0.47, intensity: 0.92,
    descriptors: ["funk", "overripe-banana", "ester", "tropical", "molasses"],
    axes: { sweet: 0.25, sour: 0.05, bitter: 0.05, strong: 0.9, aromatic: 0.85 } },
  { ref: "blackstrap-rum", ref_type: "tag", role: "base-spirit", typical_abv: 0.4, intensity: 0.9,
    descriptors: ["molasses", "burnt-sugar", "licorice", "tar", "deep-sweet"],
    axes: { sweet: 0.4, sour: 0, bitter: 0.2, strong: 0.85, aromatic: 0.7 } },
  { ref: "blanco-tequila", ref_type: "tag", role: "base-spirit", typical_abv: 0.4, intensity: 0.8,
    descriptors: ["agave", "vegetal", "citrus", "white-pepper", "mineral"],
    axes: { sweet: 0.1, sour: 0.05, bitter: 0.1, strong: 0.85, aromatic: 0.6 } },

  // ── named-product spirits ───────────────────────────────────────────────
  { ref: "buffalo-trace", ref_type: "product", role: "base-spirit", typical_abv: 0.45, intensity: 0.85,
    descriptors: ["caramel", "vanilla", "brown-sugar", "oak", "soft-spice"],
    axes: { sweet: 0.22, sour: 0, bitter: 0.1, strong: 0.9, aromatic: 0.6 } },
  { ref: "rittenhouse-rye", ref_type: "product", role: "base-spirit", typical_abv: 0.5, intensity: 0.9,
    descriptors: ["rye-spice", "pepper", "clove", "oak", "dry"],
    axes: { sweet: 0.1, sour: 0, bitter: 0.15, strong: 0.95, aromatic: 0.68 } },
  { ref: "tanqueray", ref_type: "product", role: "base-spirit", typical_abv: 0.473, intensity: 0.85,
    descriptors: ["juniper", "citrus", "pine", "crisp", "peppery"],
    axes: { sweet: 0.03, sour: 0, bitter: 0.1, strong: 0.92, aromatic: 0.78 } },
  { ref: "bacardi-superior", ref_type: "product", role: "base-spirit", typical_abv: 0.4, intensity: 0.6,
    descriptors: ["light-cane", "clean", "faint-vanilla", "almond"],
    axes: { sweet: 0.16, sour: 0, bitter: 0.03, strong: 0.85, aromatic: 0.38 } },
  { ref: "appleton-estate-reserve", ref_type: "product", role: "base-spirit", typical_abv: 0.43, intensity: 0.82,
    descriptors: ["oak", "orange-peel", "molasses", "almond", "light-funk"],
    axes: { sweet: 0.28, sour: 0, bitter: 0.06, strong: 0.88, aromatic: 0.62 } },
  { ref: "smith-and-cross", ref_type: "product", role: "base-spirit", typical_abv: 0.57, intensity: 0.97,
    descriptors: ["heavy-funk", "ester", "overripe-banana", "molasses", "fruit"],
    axes: { sweet: 0.22, sour: 0.05, bitter: 0.05, strong: 0.97, aromatic: 0.9 } },
  { ref: "cruzan-blackstrap", ref_type: "product", role: "base-spirit", typical_abv: 0.4, intensity: 0.9,
    descriptors: ["molasses", "burnt-sugar", "licorice", "deep-sweet"],
    axes: { sweet: 0.4, sour: 0, bitter: 0.2, strong: 0.85, aromatic: 0.72 } },
  { ref: "espolon-blanco", ref_type: "product", role: "base-spirit", typical_abv: 0.4, intensity: 0.82,
    descriptors: ["agave", "vegetal", "citrus", "pepper", "mineral"],
    axes: { sweet: 0.1, sour: 0.05, bitter: 0.1, strong: 0.85, aromatic: 0.62 } },

  // ── pantry / freeform (role detection for classify_family) ──────────────
  { ref: "egg-white", ref_type: "freeform", role: "egg-dairy", typical_abv: 0, intensity: 0.2,
    descriptors: ["silky", "neutral", "foam"],
    axes: { sweet: 0, sour: 0, bitter: 0, strong: 0, aromatic: 0 },
    notes: "Texture/foam, negligible flavor — its presence marks the flip/fizz root." },
  { ref: "soda", ref_type: "freeform", role: "carbonation", typical_abv: 0, intensity: 0.15,
    descriptors: ["carbonation", "neutral", "effervescent"],
    axes: { sweet: 0, sour: 0.05, bitter: 0, strong: 0, aromatic: 0 },
    notes: "Carbonated lengthener — marks the highball root and adds dilution." },
  { ref: "tonic", ref_type: "freeform", role: "carbonation", typical_abv: 0, intensity: 0.4,
    descriptors: ["quinine-bitter", "sweet", "citrus", "effervescent"],
    axes: { sweet: 0.35, sour: 0.05, bitter: 0.3, strong: 0, aromatic: 0.3 } },
  { ref: "mint", ref_type: "freeform", role: "garnish", typical_abv: 0, intensity: 0.5,
    descriptors: ["mint", "cooling", "green", "herbal"],
    axes: { sweet: 0, sour: 0, bitter: 0.05, strong: 0, aromatic: 0.7 } },
];
