#!/usr/bin/env bun
/**
 * One-shot: enrich the canonical starter catalog with §3a structured fields
 * (distillery, origin_country, origin_region, age_statement_y) and §3b
 * namespaced tags (smugglers-cove, cocktail-codex) by calling the AI gateway
 * once per product, then write the enriched data out as a TS file.
 *
 * Usage:
 *   cd packages/db
 *   bun run scripts/backfill-products.ts > seed/products.enriched.ts
 *
 * The current `seed/products.ts` is then replaced with the enriched file
 * (review the diff first). Tags ship inline on the StarterProduct shape so
 * `seed()` can insert product + tags in one pass.
 *
 * Safe to re-run — it only ever reads from CANON_PRODUCTS and writes stdout.
 */
import { lookupProduct } from "../../server/src/ai/product-lookup";
import { bootstrapGatewayKey } from "../../server/src/ai/gateway";
import { CANON_PRODUCTS } from "../seed/products";

interface Tag {
  namespace: string;
  value: string;
}

interface EnrichedProduct {
  id: string;
  name: string;
  category: string;
  subcategory: string | null;
  abv: number | null;
  default_ml: number | null;
  flavor_tags: string[];
  notes: string | null;
  distillery: string | null;
  origin_country: string | null;
  origin_region: string | null;
  age_statement_y: number | null;
  tags: Tag[];
}

async function main() {
  if (!bootstrapGatewayKey()) {
    console.error("AI_GATEWAY_API_KEY not set (no ~/.ai_gateway_api_key). Aborting.");
    process.exit(1);
  }

  const out: EnrichedProduct[] = [];
  for (const p of CANON_PRODUCTS) {
    process.stderr.write(`  enriching ${p.id} (${p.name})… `);
    try {
      const result = await lookupProduct({ name: p.name });
      if (!result.ok) {
        process.stderr.write(`SKIP (${result.reason})\n`);
        out.push(passthrough(p));
        continue;
      }
      const r = result.result;
      // Preserve operator-curated fields where they exist; only fill the gaps.
      // The current canon catalog has hand-tuned `notes`, `flavor_tags`, and
      // `subcategory` — keep those; let AI fill the rest.
      out.push({
        id: p.id,
        name: p.name,
        category: p.category,
        subcategory: p.subcategory ?? r.subcategory ?? null,
        abv: p.abv ?? r.abv,
        default_ml: p.default_ml ?? null,
        flavor_tags: p.flavor_tags.length > 0 ? p.flavor_tags : r.flavor_tags,
        notes: p.notes ?? r.notes ?? null,
        distillery: r.distillery,
        origin_country: r.origin_country,
        origin_region: r.origin_region,
        age_statement_y: r.age_statement_y,
        tags: r.tags,
      });
      process.stderr.write(
        `OK · ${r.distillery ?? "—"} · ${r.origin_country ?? "—"} · ${r.tags.length} tag${r.tags.length === 1 ? "" : "s"}\n`,
      );
    } catch (err) {
      process.stderr.write(`ERROR (${err instanceof Error ? err.message : String(err)})\n`);
      out.push(passthrough(p));
    }
  }

  process.stdout.write(serialize(out));
  process.stderr.write(`\nwrote ${out.length} products to stdout\n`);
}

function passthrough(p: (typeof CANON_PRODUCTS)[number]): EnrichedProduct {
  return {
    id: p.id,
    name: p.name,
    category: p.category,
    subcategory: p.subcategory ?? null,
    abv: p.abv ?? null,
    default_ml: p.default_ml ?? null,
    flavor_tags: [...p.flavor_tags],
    notes: p.notes ?? null,
    distillery: null,
    origin_country: null,
    origin_region: null,
    age_statement_y: null,
    tags: [],
  };
}

/**
 * Emit a TS module that exports STARTER_PRODUCTS — `seed()` consumes this
 * shape and writes product + tags in one pass. Keeping a one-file output
 * keeps git diffs auditable: each future re-run produces the same key
 * ordering, so changes show as field-level deltas.
 */
function serialize(products: EnrichedProduct[]): string {
  const lines: string[] = [
    "// AUTO-GENERATED by scripts/backfill-products.ts — do not hand-edit in bulk.",
    "// Regenerate: cd packages/db && bun run scripts/backfill-products.ts > seed/products.ts",
    "//",
    "// §3a structured fields (distillery, origin_country, origin_region, age_statement_y)",
    "// + §3b namespaced tags filled from /ai/product-lookup against Haiku 4.5.",
    "// See specs/inventory-model.md for the model.",
    "",
    'import type { Product } from "@backbar/core";',
    "",
    "/** Starter product shape — Product + optional namespaced tags for seed insertion. */",
    "export interface StarterProduct extends Product {",
    "  tags?: { namespace: string; value: string }[];",
    "}",
    "",
    "export const CANON_PRODUCTS: readonly StarterProduct[] = [",
  ];
  for (const p of products) {
    lines.push("  {");
    lines.push(`    id: ${JSON.stringify(p.id)},`);
    lines.push(`    name: ${JSON.stringify(p.name)},`);
    lines.push(`    category: ${JSON.stringify(p.category)},`);
    if (p.subcategory !== null) lines.push(`    subcategory: ${JSON.stringify(p.subcategory)},`);
    if (p.abv !== null) lines.push(`    abv: ${p.abv},`);
    if (p.default_ml !== null) lines.push(`    default_ml: ${p.default_ml},`);
    lines.push(`    flavor_tags: ${JSON.stringify(p.flavor_tags)},`);
    if (p.notes !== null) lines.push(`    notes: ${JSON.stringify(p.notes)},`);
    if (p.distillery !== null) lines.push(`    distillery: ${JSON.stringify(p.distillery)},`);
    if (p.origin_country !== null) lines.push(`    origin_country: ${JSON.stringify(p.origin_country)},`);
    if (p.origin_region !== null) lines.push(`    origin_region: ${JSON.stringify(p.origin_region)},`);
    if (p.age_statement_y !== null) lines.push(`    age_statement_y: ${p.age_statement_y},`);
    if (p.tags.length > 0) {
      lines.push(`    tags: [`);
      for (const t of p.tags) {
        lines.push(`      { namespace: ${JSON.stringify(t.namespace)}, value: ${JSON.stringify(t.value)} },`);
      }
      lines.push(`    ],`);
    }
    lines.push("  },");
  }
  lines.push("];");
  lines.push("");
  return lines.join("\n");
}

await main();
